name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm registry authentication
        run: |
              pnpm config set @icqqjs:registry https://npm.pkg.github.com/
              pnpm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
      - name: install logger dependencies
        run: pnpm --filter @zhin.js/logger install

      - name: build logger
        run: pnpm --filter @zhin.js/logger build

      - name: install cli dependencies
        run: pnpm --filter @zhin.js/cli install

      - name: build cli
        run: pnpm --filter @zhin.js/cli build
        
      - name: install dependencies
        run: pnpm install
        env:
          # NPM_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: build packages
        run: pnpm build
      
      - name: run tests
        run: pnpm test

  pub:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: install logger dependencies
        run: pnpm --filter @zhin.js/logger install

      - name: build logger
        run: pnpm --filter @zhin.js/logger build

      - name: install cli dependencies
        run: pnpm --filter @zhin.js/cli install

      - name: build cli
        run: pnpm --filter @zhin.js/cli build
        
      - name: install dependencies
        run: pnpm install
        env:
          # NPM_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: build packages
        run: pnpm build
      
      - name: bump versions
        uses: changesets/action@v1
        id: changesets
        with:
          version: pnpm bump
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm pub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
